on:
  push:
    branches:
      - main

name: Build Konekta Deployment Image
jobs:
  call-konekta-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Konekta Repository
        uses: peter-evans/workflow-dispatch@v4
        with:
          repository: cevi/konekta-webpage
          event-type: build-konekta-deployment-image
          token: ${{ secrets.KONEKTA_TOKEN }}
